### PR TITLE
Fix wallet connect modal responsivity

### LINKED ISSUE #71: Wallet connection modal not responsive
Screenshot 2022-08-01 at 17 10 16

### PR DESCRIPTION
**Pull request by Jonath-z**
close #71 
# PR Summary

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots

Screenshot from 2022-08-01 22-14-50

Screenshot from 2022-08-01 22-14-37

### CODE REVIEW

**Comment by merdikim** [comment]
@Jonath-z can we have a light gray background on the cross button that makes the modal disappear? I think it will make it stand out by default. Then on hover, it will behave just the same way it does. What do you think about that?

**Comment by Jonath-z** [comment]
let's do it ,I think it better

**Review by merdikim — COMMENTED** [review]
LGTM. But before merging this branch we could improve this a little bit. Check the image below, when we're in dark mode the modal doesn't stand out very well. We could lift it up a little bit by adding some box shadow or a small border just to make it stand out from the background in dark mode. What do you think about that
Screenshot 2022-08-05 at 21 14 55
?

**Comment by Jonath-z** [comment]
sure , I'm on t

**Pull request merged**
